[custom]
; Do not change keywords; order is priority top to bottom

ruleset=🎯 Direct,rules/ACL4SSR/Clash/LocalAreaNetwork.list
ruleset=🛑 Block,rules/ACL4SSR/Clash/BanAD.list
ruleset=🛑 Block,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
ruleset=🛑 Block,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Hijacking.list
ruleset=🍃 Clean,rules/ACL4SSR/Clash/BanProgramAD.list
ruleset=🍃 Clean,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
ruleset=🍃 Clean,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list

ruleset=🇺🇸 AI-US,https://raw.githubusercontent.com/Dethrone110/Clash_own_ruleset/optrule/ai.list
ruleset=🇺🇸 AI-US,https://raw.githubusercontent.com/Dethrone110/Clash_own_ruleset/optrule/us.list
ruleset=🇺🇸 AI-US,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🇺🇸 AI-US,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list
ruleset=🇺🇸 AI-US,[]DOMAIN-KEYWORD,truthsocial

ruleset=✖️ X,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Twitter.list

ruleset=🌍 Media,https://raw.githubusercontent.com/Dethrone110/Clash_own_ruleset/optrule/youtube.list
ruleset=🌍 Media,rules/ACL4SSR/Clash/ProxyMedia.list
ruleset=🌍 Media,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=🌍 Media,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=🌍 Media,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.list
ruleset=🌍 Media,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrimeVideo/PrimeVideo.list

ruleset=ganggang,https://raw.githubusercontent.com/Dethrone110/Clash_own_ruleset/optrule/ganggang.list

ruleset=pipi,https://raw.githubusercontent.com/Dethrone110/Clash_own_ruleset/optrule/pipi.list
ruleset=pipi,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Crypto/Crypto.list
ruleset=pipi,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Web3.list
ruleset=pipi,[]SRC-IP-CIDR,192.168.6.218/32

ruleset=📢 Social,rules/ACL4SSR/Clash/Telegram.list
ruleset=📢 Social,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Discord.list
ruleset=📢 Social,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Reddit/Reddit.list
ruleset=📢 Social,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Slack/Slack.list
ruleset=📢 Social,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/WhatsApp.list
ruleset=📢 Social,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Signal/Signal.list
ruleset=📢 Social,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Instagram/Instagram.list
ruleset=📢 Social,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Facebook.list

ruleset=🚀 Proxy,rules/ACL4SSR/Clash/ProxyLite.list
ruleset=🔒 Direct-Extra,https://raw.githubusercontent.com/Dethrone110/Clash_own_ruleset/optrule/own_direct.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
ruleset=Ⓜ️ Microsoft,rules/ACL4SSR/Clash/Microsoft.list
ruleset=🍎 Apple,rules/ACL4SSR/Clash/Apple.list
ruleset=🎯 Direct,[]GEOSITE,CN
ruleset=🚀 Proxy,[]GEOSITE,geolocation-!cn
ruleset=🎯 Direct,[]GEOIP,CN,no-resolve
ruleset=🐟 Final,[]FINAL

custom_proxy_group=🚀 Proxy`select`[]🔥 Extreme Auto`[]🇭🇰 HK Auto`[]🇺🇸 US Auto`[]🇯🇵 JPTW Auto`[]🇸🇬 SG Auto`[]♻️ Auto`[]DIRECT`.*
custom_proxy_group=♻️ Auto`url-test`.*`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔥 Extreme Auto`url-test`Extreme|Prestige`https://www.gstatic.com/generate_204`800,50,180
custom_proxy_group=🔥 Extreme Nodes`select`Extreme|Prestige

custom_proxy_group=🇭🇰 HK Auto`url-test`HK`https://www.gstatic.com/generate_204`300,50,120
custom_proxy_group=🇭🇰 HK Nodes`select`HK
custom_proxy_group=🇯🇵 JPTW Auto`url-test`JP|TW`https://www.gstatic.com/generate_204`700,50,250
custom_proxy_group=🇸🇬 SG Auto`url-test`SG`https://www.gstatic.com/generate_204`900,60,250

custom_proxy_group=🇹🇼 TW Nodes`select`TW
custom_proxy_group=🇸🇬 SG Nodes`select`SG
custom_proxy_group=🇯🇵 JPTW Nodes`select`JP|TW
custom_proxy_group=🇺🇸 US Auto`url-test`US`https://www.gstatic.com/generate_204`1200,80,250
custom_proxy_group=🇺🇸 US Nodes`select`US

custom_proxy_group=🇺🇸 AI-US`select`[]🇺🇸 US Auto`[]🇺🇸 US Nodes
custom_proxy_group=ganggang`select`[]🇭🇰 HK Auto`[]🇭🇰 HK Nodes
custom_proxy_group=pipi`select`[]🇯🇵 JPTW Auto`[]🇯🇵 JPTW Nodes`[]🇹🇼 TW Nodes`[]🇸🇬 SG Auto`[]🇸🇬 SG Nodes`[]🇭🇰 HK Auto`[]🇭🇰 HK Nodes

custom_proxy_group=🌍 Media`select`[]🔥 Extreme Auto`[]🔥 Extreme Nodes`[]🇺🇸 US Auto`[]🇺🇸 US Nodes`[]🇭🇰 HK Auto`[]🇭🇰 HK Nodes`[]🇯🇵 JPTW Auto`[]🇯🇵 JPTW Nodes`[]🇹🇼 TW Nodes`[]🇸🇬 SG Auto`[]🇸🇬 SG Nodes`[]♻️ Auto`[]🚀 Proxy`[]🎯 Direct`.*
custom_proxy_group=📢 Social`select`[]🇭🇰 HK Auto`[]🇭🇰 HK Nodes`[]🇹🇼 TW Nodes`[]🇸🇬 SG Auto`[]🇸🇬 SG Nodes`[]🇺🇸 US Auto`[]🇺🇸 US Nodes`[]🇯🇵 JPTW Auto`[]🇯🇵 JPTW Nodes`[]🔥 Extreme Auto`[]♻️ Auto`[]🚀 Proxy`[]🎯 Direct`.*
custom_proxy_group=✖️ X`select`[]🇭🇰 HK Auto`[]🇭🇰 HK Nodes`[]🇹🇼 TW Nodes`[]🇸🇬 SG Auto`[]🇸🇬 SG Nodes`[]🇺🇸 US Auto`[]🇺🇸 US Nodes`[]🇯🇵 JPTW Auto`[]🇯🇵 JPTW Nodes`[]🔥 Extreme Auto`[]♻️ Auto`[]🚀 Proxy`[]🎯 Direct`.*
custom_proxy_group=Ⓜ️ Microsoft`select`[]🔥 Extreme Auto`[]🇺🇸 US Auto`[]🇺🇸 US Nodes`[]🇯🇵 JPTW Auto`[]🇯🇵 JPTW Nodes`[]🇹🇼 TW Nodes`[]🇸🇬 SG Auto`[]🇸🇬 SG Nodes`[]♻️ Auto`[]🎯 Direct`[]🚀 Proxy`.*
custom_proxy_group=🍎 Apple`select`[]🔥 Extreme Auto`[]🇺🇸 US Auto`[]🇺🇸 US Nodes`[]🇯🇵 JPTW Auto`[]🇯🇵 JPTW Nodes`[]🇹🇼 TW Nodes`[]🇸🇬 SG Auto`[]🇸🇬 SG Nodes`[]♻️ Auto`[]🚀 Proxy`[]🎯 Direct`.*
custom_proxy_group=🎯 Direct`select`[]DIRECT`[]🚀 Proxy`[]♻️ Auto
custom_proxy_group=🛑 Block`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 Clean`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 Final`select`[]🚀 Proxy`[]🎯 Direct`[]♻️ Auto`.*
custom_proxy_group=🔒 Direct-Extra`select`[]DIRECT

[dns]
enable=true
listen=:53
enhanced-mode=fake-ip
fake-ip-range=198.18.0.1/16
default-nameserver=tls://223.5.5.5:853,tls://119.29.29.29:853,tls://1.1.1.1:853
nameserver=https://dns.alidns.com/dns-query,https://doh.pub/dns-query
fallback=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query,https://dns.quad9.net/dns-query
fallback-filter:
  geoip=true
  geoip-code=CN
  ipcidr=0.0.0.0/32
proxy-server-nameserver=https://dns.alidns.com/dns-query,https://doh.pub/dns-query,https://1.1.1.1/dns-query
